// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireconfig

import (
	"database/sql"
	"github.com/ramailh/technical-test-dbo/internal/common/config/redis"
	postgres2 "github.com/ramailh/technical-test-dbo/internal/repository/auth/postgres"
	"github.com/ramailh/technical-test-dbo/internal/repository/customer/postgres"
	"github.com/ramailh/technical-test-dbo/internal/service/auth"
	"github.com/ramailh/technical-test-dbo/internal/service/customer"
	"github.com/ramailh/technical-test-dbo/internal/transport/http/customer/controller"
)

// Injectors from customer_wire.go:

func InitializeCustomerController(pg *sql.DB, rds redis.Redis) (controller.CustomerController, error) {
	customerRepository := postgres.NewCustomerRepository(pg)
	authRepository := postgres2.NewAuthRepository(pg)
	authService := auth.NewAuthService(authRepository, rds)
	customerService := customer.NewCustomerService(customerRepository, authService, rds)
	customerController := controller.NewCustomerController(customerService)
	return customerController, nil
}
