// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireconfig

import (
	"database/sql"
	"github.com/ramailh/technical-test-dbo/internal/common/config/redis"
	"github.com/ramailh/technical-test-dbo/internal/repository/auth/postgres"
	"github.com/ramailh/technical-test-dbo/internal/service/auth"
	"github.com/ramailh/technical-test-dbo/internal/transport/http/auth/controller"
)

// Injectors from wire.go:

func InitializeAuthController(pg *sql.DB, rds redis.Redis) (controller.AuthController, error) {
	authRepository := postgres.NewAuthRepository(pg)
	authService := auth.NewAuthService(authRepository, rds)
	authController := controller.NewAuthController(authService)
	return authController, nil
}
